config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  resources :tasks
  resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/user/:id/account', to: 'users#account', as: 'user_account'
  post '/advance-category', to: 'tasks#advance_category', as: 'advance_category'
  post '/back-category', to: 'tasks#back_category', as: 'back_category'
  get 'project/:id/my_tasks', to: 'projects#my_tasks', as: 'my_tasks'
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :projects, only: [:show] do
    resources :tasks, only: [:new, :show]
  end

  get '*path', to: 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates_presence_of :due_date, :description, :category

  scope :category_tasks, ->(cat) { where(category: cat) }
  scope :count_tasks_by_user, ->(user) { where(user_id: user.id).count }
  scope :count_tasks_by_project, ->(project) { where(project_id: project.id).count }
  scope :next_five_tasks, ->(user) { where(user_id: user.id).where("due_date > ?", Date.today).where("category != ?", "Complete").order(:due_date).limit(5)}
  scope :order_by_due_date_and_priority, -> { order(:due_date).order(:priority) }
  scope :user_tasks, ->(user) { where(user_id: user.id)}
  scope :project_user_tasks, ->(project, user) { where(project_id: project.id).where(user_id: user.id) }

  PRIORITY = [
    ["High", 0],
    ["Medium", 1],
    ["Low", 2]
  ]

  def change_category(data)
    category_array = ["Future", "Current", "Complete"]
    category_index = category_array.find_index("#{self.category}")
    forward_index = category_index + 1 unless category_index == category_array.length - 1
    backward_index = category_index - 1 unless category_index == 0
    if data == "+"
      f = forward_index ||= category_array.length - 1
      self.update(category: category_array[f])
    elsif data == "-"
      b = backward_index ||= 0
      self.update(category: category_array[b])
    end
  end
  # in the future, this method could take in data and a category_array
  # that way the user could set their own categories and the back and forward buttons
  # would still work
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :advance_category, :back_category, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update, :advance_category, :back_category, :destroy]
  
  def index
    @tasks = Project.public_projects.collect {|p| p.tasks }.flatten
  end

  def new
    @task = Task.new(project_id: params[:project_id], user_id: current_user.id)
  end

  def create
    @task = Task.create(task_params)
    if @task.save
      redirect_to project_path(@task.project)
    else
      render :new
    end
  end

  def show
    redirect_to user_path(current_user), alert: 'You do not have access to view this task.' unless @task.project.owner_object.public 
  end

  def edit
  end

  def update
    @task.update(task_params)
    if @task.valid?
      redirect_to project_path(@task.project), alert: "Task successfully updated."
    else
      render :edit
    end
  end

  def advance_category
    @task.change_category("+")
    redirect_to project_path(@task.project)
  end

  def back_category
    @task.change_category("-")
    redirect_to project_path(@task.project)
  end

  def destroy
    project = @task.project
    @task.delete
    redirect_to project_path(project)
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :project_id, :due_date, :description, :priority, :category)
  end

  def set_task
    @task = Task.find_by(id: params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def project_id_field(task)
    if task.project.nil?
      select_tag "task[project_id]", options_from_collection_for_select(Project.all, :id, :title), { prompt: 'Select Project' }
    else
      hidden_field_tag "task[project_id]", task.project.id
    end
  end
end

app/views/tasks/_form.html.erb
<%= f.hidden_field :user_id %>
<%= project_id_field(@task) %><br><br>

<%= f.label :due_date, "Due Date" %><br>
<%= f.date_field :due_date %><br><br>

<%= f.label :description %><br>
<%= f.text_area :description %><br><br>

<%= f.select :priority, Task::PRIORITY, prompt: 'Select Priority' %><br><br>

<%= f.select :category, ['Future','Current','Complete'], prompt: 'Select Category' %><br><br>

app/views/tasks/_task.html.erb
<% if task.project %>
  <li><%= link_to "#{task.description}", project_task_path(task.project, task) %>, due: <%= task.due_date.strftime("%B %-d, %Y") %>, assigned to: <%= link_to "#{task.user.username}", user_path(task.user) %></li>
<% else %>
  <li><%= link_to "#{task.description}", task_path(task) %> - no project assigned, due: <%= task.due_date.strftime("%B %-d, %Y") %>, assigned to: <%= link_to "#{task.user.username}", user_path(task.user) %></li>
<% end %>

app/views/tasks/edit.html.erb
<%= render partial: 'projects/errors', locals: {project: @task} %>
<br>
<h2>Edit Task</h2>
<%= form_for @task do |f| %>
  <%= render partial: 'form', locals: {f: f} %>

  <%= f.submit "Update Task" %>
<% end %>
<br><br><br>

app/views/tasks/index.html.erb
<br>
<h1>iKanBan - Public Tasks</h1>

  <ul>
    <%= render @tasks %>
  </ul>

app/views/tasks/new.html.erb
<%= render partial: 'projects/errors', locals: {project: @task} %>
<br>
<h2>New Task</h2>
<%= form_for @task do |f| %>
  <%= render partial: 'form', locals: {f: f} %>

  <%= f.submit "Save Task" %>
<% end %>
<br><br><br>

app/views/tasks/show.html.erb
<h4><%= @task.description %>, added by <%= link_to @task.user.username, user_path(@task.user) %></h4><br><br>

<% if @task.project %> 
  Project Board: <%= @task.project.title %>, created by <%= link_to @task.project.owner_object.username, user_path(@task.project.owner_object) %><br><br>
<% end %>

Due <%= @task.due_date.strftime("%B %-d, %Y") %><br><br>

<%= task_priority(@task) %> Priority<br><br>

Stage in Process: <%= @task.category %> Task<br><br>

<%= button_to "Back to Project", project_path(@task.project), method: :get, form: {style: 'display:inline-block;'} unless !@task.project %>

<% if @task.user == current_user %>
  <%= button_to "Edit Task", edit_task_path(@task), method: :get, form: {style: 'display:inline-block;'} %>
  <%= button_to "Delete Task", task_path(@task), method: :delete, form: {style: 'display:inline-block;'}, data: {confirm: 'Are you sure?'} %>
<% end %>
  <br><br><br>