config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  resources :tasks
  resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/user/:id/account', to: 'users#account', as: 'user_account'
  post '/advance-category', to: 'tasks#advance_category', as: 'advance_category'
  post '/back-category', to: 'tasks#back_category', as: 'back_category'
  get 'project/:id/my_tasks', to: 'projects#my_tasks', as: 'my_tasks'
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :projects, only: [:show] do
    resources :tasks, only: [:new, :show]
  end

  get '*path', to: 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :projects, through: :tasks

  has_secure_password
  
  validates_presence_of :username, :email, :first_name, :last_name
  validates_uniqueness_of :username, :email
  validates_length_of :password, in: 6..40, on: :create, message: " must be 6-40 characters."
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create, message: "Email address must be valid."

  scope :public_users, -> { where(public: true) }

  def owned_projects
    Project.where(owner: self.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:account, :edit, :update, :destroy]
  before_action :set_user, only: [:account, :edit, :update]

  def index
    @public_users = User.public_users
  end
  
  def new
    redirect_to user_path(current_user) unless !current_user
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    if !@user.nil?
      @projects = @user.projects
      @next_five_tasks = Task.next_five_tasks(@user)
      redirect_to user_path(current_user), alert: "User not found." unless @user.public || @user == current_user
    else
      redirect_to root_path, alert: "User not found."
    end
  end

  def account
    @total_task_count = Task.count_tasks_by_user(@user)
    @complete_task_count = Task.category_tasks("Complete").count_tasks_by_user(@user)
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.valid?
      redirect_to user_path(@user), alert: "Account successfully updated."
    else
      render :edit
    end
  end

  def destroy
    user = User.find_by(id: session[:user_id])
    user.delete
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :organization, :password, :password_confirmation, :public)
  end

  def set_user
    @user = current_user
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= f.label :username %>
<%= f.text_field :username %><br><br>

<%= f.label :first_name, "First Name" %>
<%= f.text_field :first_name %><br><br>

<%= f.label :last_name, "Last Name" %>
<%= f.text_field :last_name %><br><br>

<%= f.label :email %>
<%= f.text_field :email %><br><br>

<%= f.label :organization %>
<%= f.text_field :organization %><br><br>

<%= f.label :password %>
<%= f.password_field :password %><br><br>

<%= f.label :password_confirmation, "Password Confirmation" %>
<%= f.password_field :password_confirmation %><br><br>

<%= f.label :public %>
<%= f.check_box :public %><br><br>

app/views/users/_project.html.erb
<li><%= link_to "#{project.title}", project_path(project) %></li>

app/views/users/account.html.erb
<%# Where private user information can be stored %>
<br>
<h3><%= @user.username %>'s iKanBan Stats</h3>
<%= @user.owned_projects.count %> project board(s) created<br>
<%= @total_task_count %> task(s) created<br>
<%= @complete_task_count %> task(s) completed<br><br>

<%= button_to "Edit my account information", edit_user_path(@user), method: :get, form: {style: 'display:inline-block;'} %>
<%= button_to "Delete my account", user_path(@user), method: :delete, data: {confirm: 'Are you sure?'}, form: {style: 'display:inline-block;'} %>
<br><br><br>

app/views/users/edit.html.erb
<%= render partial: 'projects/errors', locals: {project: @user} %>
<br>
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit "Update" %>
<% end %>

app/views/users/index.html.erb
<br>
<h1>iKanBan Users</h1>
<h3>Click a username to see their current projects!</h3>
<% @public_users.each do |user| %>
  <%= link_to user.username, user_path(user) %><br>
<% end %>
<p><em>Note: this list does not include users with private accounts.</em></p>

app/views/users/new.html.erb
<%= render partial: 'projects/errors', locals: {project: @user} %>
<br>
<h1>iKanBan Signup</h1>
<h3>Sign up to take full advantage of iKanBan's features!</h3>
<%= form_for @user do |f| %>
  <%= render partial: 'form', locals: {f: f} %><br><br>
  <%= f.submit "Create New User" %>
<% end %>

<h3>Login with Google</h3>
<%= button_to 'Google', '/auth/google_oauth2' %>

app/views/users/show.html.erb
<br>
<% if @user == current_user %>
  <h1>Welcome, <%= @user.first_name %>!</h1><br>
  <%= button_to "New Project", new_project_path, method: :get %>
  <h3>My Project Boards</h3>
    <ul>
    <% if @user.owned_projects.empty? %>
      <li>No current projects</li>
    <% else %>
      <%= render partial: 'project', collection: @user.owned_projects %>
    <% end %>
    </ul>
  
  <h3>My Upcoming Tasks</h3>
    <ul>
    <% if @next_five_tasks.count == 0 %>
      <li>No upcoming tasks!</li>
    <% else %>
      <% @next_five_tasks.each do |t| %>
        <li><%= link_to "#{t.description}", project_task_path(project_id: t.project_id, id: t.id) %>, due <%= t.due_date.strftime("%B %-d, %Y") %>, priority: <%= task_priority(t) %></li>  
      <% end %>
    <% end %>
    </ul>

<% else %>
  <h1>You are viewing <%= @user.first_name %>'s public projects page!</h1><br>

  <h3><%= @user.first_name %>'s Project Boards:</h3>
    <ul>
    <% if @user.owned_projects.empty? %>
      <li>No current projects</li>
    <% else %>
      <%= render partial: 'project', collection: @user.owned_projects %>
    <% end %>
    </ul>
<% end %>

<br><br>