config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  resources :tasks
  resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/user/:id/account', to: 'users#account', as: 'user_account'
  post '/advance-category', to: 'tasks#advance_category', as: 'advance_category'
  post '/back-category', to: 'tasks#back_category', as: 'back_category'
  get 'project/:id/my_tasks', to: 'projects#my_tasks', as: 'my_tasks'
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :projects, only: [:show] do
    resources :tasks, only: [:new, :show]
  end

  get '*path', to: 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_many :users, through: :tasks

  validates_presence_of :title, :description

  def owner_object
    User.find_by(id: self.owner)
  end

  def task_type(category)
    self.tasks.where(category: "#{category}")
  end

  scope :public_projects, -> { joins('INNER JOIN users ON projects.owner = users.id').where('users.public = true')}

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ProjectsHelper

  before_action :set_project, only: [:show, :edit, :update, :my_tasks, :destroy]
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def index
    @projects = Project.public_projects
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show 
    redirect_to user_path(current_user), alert: 'You do not have access to view this project.' unless @project.owner_object.public || @project.owner_object == current_user
  end

  def edit
  end

  def update
    @project.update(project_params)
    if @project.save
      redirect_to project_path(@project), alert: "Project successfully updated."
    else
      render :edit
    end
  end

  def my_tasks
    @future_tasks = Task.project_user_tasks(@project, current_user).category_tasks("Future").order_by_due_date_and_priority
    @current_tasks = Task.project_user_tasks(@project, current_user).category_tasks("Current").order_by_due_date_and_priority
    @complete_tasks = Task.project_user_tasks(@project, current_user).category_tasks("Complete").order_by_due_date_and_priority
  end

  def destroy
    @project.tasks.each {|t| t.delete}
    @project.delete
    redirect_to user_path(current_user), alert: "Project deleted."
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :organization, :owner)
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def contributor(project, user)
    project.tasks.collect {|t| t.user_id}.include?(user.id)
  end
end

app/views/projects/_errors.html.erb
<% if project.errors.any? %>
  <div id = "error_explanation".
    <h2>
      <%= pluralize(project.errors.count, "error") %> prohibited this item from being saved:
    </h2>
    <ul>
    <% project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/projects/_form.html.erb
<%= f.hidden_field :owner, value: session[:user_id] %>

<%= f.label :title %>
<%= f.text_field :title %><br><br>

<%= f.label :description %><br>
<%= f.text_area :description %><br><br>

<%= f.label :organization %>
<%= f.text_field :organization %><br><br>

app/views/projects/_task.html.erb
<div class="#{type.lowercase}" style="width: 33%; float: left">
<h3><%= type %> Tasks </h3>
<ul>
<% @project.task_type("#{type}").order_by_due_date_and_priority.each do |t| %>
  <li><%= link_to "#{t.description}", project_task_path(project_id: t.project.id, id: t.id) %>  
  <%= button_to "<", {controller: :tasks, action: :back_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  <%= button_to ">", {controller: :tasks, action: :advance_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  </li>
    <ul>
      <li>Due <%= t.due_date %>, <%= task_priority(t) %> Priority</li>
    </ul><br>
<% end %>
</ul>
<br><br>
</div>

app/views/projects/edit.html.erb
<%= render partial: 'errors', locals: {project: @project} %>
<br>
<h3>Edit Project Board</h3><br>
<%= form_for @project do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit "Update" %>
<% end %>
<br><br><br>

app/views/projects/index.html.erb
<br>
<h1>iKanBan Projects</h1>
<h3>Click a project name to see details or add tasks.</h3>
  <ul>
  <% if @projects.empty? %>
    <li>No current projects</li>
  <% else %>
    <%= render partial: 'users/project', collection: @projects %>
  <% end %>
  </ul>

app/views/projects/my_tasks.html.erb
<br>
<h1 style="text-align: center"><%= @project.title %></h1>
<h3 style="text-align: center"><%= @project.description %></h3>

<div style="width: 33%; margin: auto">
<%= button_to "Show All Tasks", project_path(@project), method: :get, form: {style: 'display:inline-block;'} %>
<%= button_to "Add Task", new_project_task_path(project_id: @project.id), method: :get, form: {style: 'display:inline-block;'} %>
<% if current_user && current_user.id == @project.owner %>
  <%= button_to "Edit Project", edit_project_path(@project), method: :get, form: {style: 'display:inline-block;'} %>
  <%= button_to "Delete Project", project_path(@project), method: :delete, form: {style: 'display:inline-block;'}, data: {confirm: 'Are you sure? This will destroy the project and all associated tasks.'} %>
<% end %>
  <br><br><br>
</div>

<div class="future" style="width: 33%; float: left">
<h3>Future Tasks </h3>
<ul>
<% @future_tasks.each do |t| %>
  <li><%= link_to "#{t.description}", project_task_path(project_id: t.project.id, id: t.id) %>  
  <%= button_to "<", {controller: :tasks, action: :back_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  <%= button_to ">", {controller: :tasks, action: :advance_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  </li>
    <ul>
      <li>Due <%= t.due_date %>, <%= task_priority(t) %> Priority</li>
    </ul><br>
<% end %>
</ul>
<br><br>
</div>

<div class="current" style="width: 33%; float: left">
<h3>Current Tasks </h3>
<ul>
<% @current_tasks.each do |t| %>
  <li><%= link_to "#{t.description}", project_task_path(project_id: t.project.id, id: t.id) %>  
  <%= button_to "<", {controller: :tasks, action: :back_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  <%= button_to ">", {controller: :tasks, action: :advance_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  </li>
    <ul>
      <li>Due <%= t.due_date %>, <%= task_priority(t) %> Priority</li>
    </ul><br>
<% end %>
</ul>
<br><br>
</div>

<div class="complete" style="width: 33%; float: left">
<h3>Complete Tasks </h3>
<ul>
<% @complete_tasks.each do |t| %>
  <li><%= link_to "#{t.description}", project_task_path(project_id: t.project.id, id: t.id) %>  
  <%= button_to "<", {controller: :tasks, action: :back_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  <%= button_to ">", {controller: :tasks, action: :advance_category, id: t.id}, method: :post, form: {style: 'display:inline-block;'} %>
  </li>
    <ul>
      <li>Due <%= t.due_date %>, <%= task_priority(t) %> Priority</li>
    </ul><br>
<% end %>
</ul>
<br><br>
</div>

app/views/projects/new.html.erb
<%= render partial: 'errors', locals: {project: @project} %>
<br>
<h3>Create a New Project Board</h3><br>
<%= form_for @project do |f| %>
  <%= render partial: 'form', locals: {f: f} %>
  <%= f.submit "Create" %>
<% end %>
<br><br><br>

app/views/projects/show.html.erb
<br>
<h1 style="text-align: center"><%= @project.title %></h1>
<h3 style="text-align: center"><%= @project.description %></h3>

<div style="width: 33%; margin: auto">
<%= button_to "Show Only My Tasks", my_tasks_path(@project), method: :get, form: {style: 'display:inline-block;'} %>
<%= button_to "Add Task", new_project_task_path(project_id: @project.id), method: :get, form: {style: 'display:inline-block;'} %>
<% if current_user && current_user.id == @project.owner %>
  <%= button_to "Edit Project", edit_project_path(@project), method: :get, form: {style: 'display:inline-block;'} %>
  <%= button_to "Delete Project", project_path(@project), method: :delete, form: {style: 'display:inline-block;'}, data: {confirm: 'Are you sure? This will destroy the project and all associated tasks.'} %>
<% end %>
  <br><br><br>
</div>

<% categories.each do |c| %>
  <%= render partial: 'task', locals: {type: "#{c}"} %>
<% end %>