config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'

  resources :tasks
  resources :projects, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :users

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/user/:id/account', to: 'users#account', as: 'user_account'
  post '/advance-category', to: 'tasks#advance_category', as: 'advance_category'
  post '/back-category', to: 'tasks#back_category', as: 'back_category'
  get 'project/:id/my_tasks', to: 'projects#my_tasks', as: 'my_tasks'
  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :projects, only: [:show] do
    resources :tasks, only: [:new, :show]
  end

  get '*path', to: 'sessions#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IKanban</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <br>
    <%= flash_alert? %>
    <div class="navbar" style="width:100%; float:left">
    <% if current_user %>
      <%= link_to "Home", user_path(current_user) %>
      <%= link_to "Account", user_account_path(current_user) %>
      <%= link_to "Users", users_path %>
      <%= link_to "Projects", projects_path %>
      <%= link_to "Log Out", logout_path, method: :post %>
    <% else %>
      <%= link_to "Home", root_path %>
      <%= link_to "Login", login_path %>
      <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <br><br><br>
  </div>
    <%= yield %>
  </body>
</html>